services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ideology
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  api:
    image: crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com/seclabx/seclabx-edu-sc:latest
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./data/uploads:/data/uploads
      - ./frontend/public/sample-files:/data/sample-files:ro

  web:
    image: crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com/seclabx/seclabx-edu-sc-web:latest
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
